### ISSUE TITLE
Please subscribe to AtmJobTask instead of AtmJob

### ISSUE THREAD

**Issue by kipz** [atomist/card-automation#10]
We'd like to transition to only firing AtmJob events for job related lifecycle events (right now, that's just created/completed).

You can link to `job` in your subscription if you subscribe AtmJobTask

**Comment by cdupuis** [comment]
There are quite a few places that needs to get changed.

**Comment by kipz** [comment]
Do you mean other sdms/automations/sdm-packs than this one?

**Comment by cdupuis** [comment]
Yes

**Comment by kipz** [comment]
Understood. Do you have that list available please?

This would effectively halve the number of events we fire for onboarding, so pretty strategic I think.
