### ISSUE TITLE
Provide data in card for rendering in web-app dialogs

### ISSUE THREAD

**Issue by jrday** [atomist/card-automation#7]
The dialogs in web-app should get the same data as chat for consistency. 

A Slack cancel goals dialog:

<img width="526" alt="Screen Shot 2019-06-25 at 15 39 22" src="https://user-images.githubusercontent.com/774714/60143857-1624f780-9775-11e9-874a-ced7bda24e13.png">

A similar dialog in web-app:

<img width="1596" alt="Screen Shot 2019-06-25 at 18 17 30" src="https://user-images.githubusercontent.com/774714/60143984-a8c59680-9775-11e9-893c-7b807254c249.png">

@drewmca has details on the differing payloads – the card pushed is not getting the same data as the chat message.

**Comment by cdupuis** [comment]
Issue moved to atomist/sdm-pack-lifecycle#10
